language: swift
   
before_install:    
    - rvm use system
    - sudo gem install cocoapods -v '0.39.0'

osx_image: xcode7.3

script:    
    xctool -workspace TVShowsReminder.xcworkspace -scheme TVShowsReminder build -sdk iphonesimulator
